# Generated by Django 4.0.6 on 2022-08-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teka', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='to_see',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
