# Generated by Django 4.0.6 on 2022-08-16 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teka', '0002_person_to_see'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='to_see',
        ),
    ]
