# Generated by Django 4.0.6 on 2022-08-18 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teka', '0004_factor_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Teka.person'),
        ),
        migrations.AlterField(
            model_name='factor',
            name='profil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Teka.profil'),
        ),
    ]
