# Generated by Django 4.0.6 on 2022-11-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teka', '0005_alter_factor_person_alter_factor_profil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='items_bought',
        ),
        migrations.AddField(
            model_name='client',
            name='transactions_done',
            field=models.ManyToManyField(blank=True, related_name='after_payment_transactions', to='Teka.transaction'),
        ),
    ]
