# Generated by Django 4.0.6 on 2022-11-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teka', '0006_remove_client_items_bought_client_transactions_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('mtn', 'MTN Mobile money'), ('air', 'Airtel money'), ('ora', 'Orange money'), ('mas', 'MasterCard'), ('pay', 'Paypal'), ('str', 'Stripe')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('I', 'Initial'), ('D', 'Done'), ('F', 'Failed')], default='I', max_length=1),
        ),
    ]
