# Generated by Django 4.0.6 on 2022-12-13 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teka', '0008_transaction_ordered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('I', 'Initial'), ('D', 'Done'), ('F', 'Failed'), ('W', 'Waiting')], default='I', max_length=1),
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('I', 'Initial'), ('D', 'Done'), ('F', 'Failed'), ('W', 'Waiting')], default='I', max_length=1)),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Teka.person')),
                ('transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Teka.transaction')),
            ],
        ),
    ]
