# Generated by Django 4.0.6 on 2022-12-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teka', '0009_alter_transaction_status_exchange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchange',
            name='transaction',
        ),
        migrations.AddField(
            model_name='exchange',
            name='exchange_type',
            field=models.CharField(choices=[('D', 'Depot'), ('R', 'Revocation')], default='D', max_length=1),
            preserve_default=False,
        ),
    ]
