# Generated by Django 4.0.6 on 2022-12-13 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teka', '0010_remove_exchange_transaction_exchange_exchange_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
