# Generated by Django 4.0.6 on 2023-01-06 19:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Teka', '0012_item_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='ordered_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 1, 6, 19, 50, 59, 698480, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
