# Generated by Django 4.0.6 on 2023-01-10 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teka', '0013_alter_transaction_ordered_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='item_state',
            field=models.CharField(choices=[('nw', 'New'), ('ud', 'Used')], default='nw', max_length=2),
        ),
    ]
