# Generated by Django 4.0.6 on 2023-01-10 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teka', '0014_person_item_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='item_state',
        ),
        migrations.AddField(
            model_name='item',
            name='item_state',
            field=models.CharField(choices=[('nw', 'New'), ('ud', 'Used')], default='nw', max_length=2),
        ),
    ]
