# Generated by Django 4.0.6 on 2023-02-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teka', '0015_remove_person_item_state_item_item_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='try',
            name='the_file',
            field=models.ImageField(blank=True, null=True, upload_to='try-only/images'),
        ),
    ]
