# Generated by Django 4.0.6 on 2023-02-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teka', '0016_try_the_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='factor',
            name='followers',
            field=models.ManyToManyField(related_name='followers', to='Teka.client'),
        ),
    ]
