# Generated by Django 4.0.6 on 2023-03-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teka', '0017_factor_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='resalable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='factor',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followers', to='Teka.client'),
        ),
    ]
