# Generated by Django 4.0.6 on 2023-03-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teka', '0018_item_resalable_alter_factor_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='factor',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='own_collaborators', to='Teka.factor'),
        ),
    ]
