# Generated by Django 4.0.6 on 2023-03-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teka', '0019_factor_collaborators'),
    ]

    operations = [
        migrations.AddField(
            model_name='factor',
            name='collab_guest',
            field=models.ManyToManyField(blank=True, related_name='collaboration_guest', to='Teka.factor'),
        ),
    ]
