# Generated by Django 4.0.6 on 2023-03-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teka', '0023_notification_item_notification_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='factor',
            name='notifications_not_opened',
            field=models.ManyToManyField(blank=True, related_name='notifications_not_opened', to='Teka.notification'),
        ),
        migrations.AddField(
            model_name='person',
            name='notifications_not_opened',
            field=models.ManyToManyField(blank=True, related_name='notifications_person_not_opened', to='Teka.notification'),
        ),
        migrations.AlterField(
            model_name='factor',
            name='notifications',
            field=models.ManyToManyField(blank=True, related_name='all_notifications', to='Teka.notification'),
        ),
        migrations.AlterField(
            model_name='person',
            name='notifications',
            field=models.ManyToManyField(blank=True, related_name='all_person_notifications', to='Teka.notification'),
        ),
    ]
