# Generated by Django 4.0.6 on 2023-03-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teka', '0025_remove_factor_notifications_not_opened_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='notifications',
            field=models.ManyToManyField(blank=True, related_name='all_factor_notifications', to='Teka.notification'),
        ),
        migrations.AlterField(
            model_name='factor',
            name='notifications_opened',
            field=models.ManyToManyField(blank=True, related_name='notifications_factor_opened', to='Teka.notification'),
        ),
    ]
