# Generated by Django 4.0.6 on 2023-04-02 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teka', '0030_factor_certified'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='factor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Teka.factor'),
        ),
    ]
