# Generated by Django 4.0.6 on 2023-04-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teka', '0031_notification_factor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaboration',
            name='activated',
            field=models.BooleanField(default=True),
        ),
    ]
