# Generated by Django 4.0.6 on 2023-04-07 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teka', '0032_alter_collaboration_activated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='resalable',
            new_name='resellable',
        ),
    ]
