# Generated by Django 4.0.6 on 2023-04-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teka', '0033_rename_resalable_item_resellable'),
    ]

    operations = [
        migrations.AddField(
            model_name='factor',
            name='collab_asked',
            field=models.ManyToManyField(blank=True, related_name='collaboration_asked', to='Teka.factor'),
        ),
    ]
