# Generated by Django 4.0.6 on 2023-04-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teka', '0034_factor_collab_asked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factor',
            name='collab_guest',
        ),
        migrations.AddField(
            model_name='factor',
            name='collab_received',
            field=models.ManyToManyField(blank=True, related_name='collaboration_received', to='Teka.factor'),
        ),
    ]
