# Generated by Django 4.0.6 on 2023-05-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teka', '0036_factor_items_collaboration'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='title',
            field=models.CharField(default='imo', max_length=255),
        ),
    ]
