# Generated by Django 4.0.6 on 2023-05-12 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teka', '0037_profil_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collabitem',
            old_name='stock_collab',
            new_name='sale',
        ),
    ]
