# Generated by Django 4.0.6 on 2023-05-12 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teka', '0039_rename_sale_collabitem_item_sales'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collabitem',
            old_name='item_sales',
            new_name='nb_sales',
        ),
    ]
