# Generated by Django 4.0.6 on 2023-05-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teka', '0040_rename_item_sales_collabitem_nb_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collabitem',
            name='nb_sales',
            field=models.IntegerField(default=0),
        ),
    ]
