# Generated by Django 4.0.6 on 2023-06-05 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teka', '0041_alter_collabitem_nb_sales'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teka.item')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teka.person')),
            ],
        ),
    ]
