# Generated by Django 4.0.6 on 2024-05-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teka', '0044_client_latitude_client_longitude_factor_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_currency',
            field=models.CharField(choices=[('xaf', 'francs CFA'), ('eur', 'euros'), ('dol', 'dollars')], default='xaf', max_length=3),
        ),
    ]
