# Generated by Django 4.0.6 on 2024-05-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teka', '0045_item_item_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_currency',
            field=models.CharField(choices=[('xaf', 'francs CFA'), ('eur', 'euros'), ('usd', 'dollars')], default='xaf', max_length=3),
        ),
    ]
