# Generated by Django 4.0.6 on 2024-05-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teka', '0047_alter_item_discount_price_alter_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='favorite_currency',
            field=models.CharField(choices=[('xaf', 'francs CFA'), ('eur', 'euros'), ('usd', 'dollars')], default='xaf', max_length=3),
        ),
    ]
