# Generated by Django 4.0.6 on 2024-06-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teka', '0049_alter_item_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_currency',
            field=models.CharField(choices=[('xaf', 'francs CFA'), ('eur', 'euros'), ('usd', 'dollars')], default='eur', max_length=3),
        ),
        migrations.AlterField(
            model_name='person',
            name='favorite_currency',
            field=models.CharField(choices=[('xaf', 'francs CFA'), ('eur', 'euros'), ('usd', 'dollars')], default='eur', max_length=3),
        ),
    ]
