# Generated by Django 4.0.6 on 2024-06-12 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teka', '0050_alter_item_item_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='type_file',
        ),
    ]
