# Generated by Django 4.0.6 on 2024-06-12 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teka', '0051_remove_media_type_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='media',
        ),
        migrations.AddField(
            model_name='item',
            name='medias',
            field=models.ManyToManyField(blank=True, limit_choices_to=5, null=True, to='Teka.media'),
        ),
    ]
