# Generated by Django 4.0.6 on 2024-06-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teka', '0052_remove_item_media_item_medias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='medias',
            field=models.ManyToManyField(blank=True, max_length=5, null=True, to='Teka.media'),
        ),
    ]
