# Generated by Django 4.0.6 on 2024-06-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teka', '0053_alter_item_medias'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='likers',
            field=models.ManyToManyField(blank=True, null=True, to='Teka.person'),
        ),
    ]
